export const atracacaoHeader = {
    Ano: true,
    "Apelido Instalação Portuária": true,
    Berço: true,
    CDTUP: true,
    "Complexo Portuário": true,
    Coordenadas: true,
    Data: true,
    "Data Atracação": true,
    "Data Chegada": true,
    "Data Desatracação": true,
    "Data Início Operação": true,
    "Data Término Operação": true,
    FlagMCOperacaoAtracacao: true,
    IDAtracacao: true,
    IDBerco: true,
    Latitude: true,
    Longitude: true,
    Mes: true,
    Municipio_sigla: true,
    Municipio: true,
    "Nacionalidade do Armador": true,
    "Nº da Capitania": true,
    "Nº do IMO": true,
    "Porto Atracação": true,
    "Região Geográfica": true,
    SGUF: true,
    Terminal: true,
    "Tipo da Autoridade Portuária": true,
    "Tipo de Navegação da Atracação": true,
    "Tipo de Operação": true,
    UF: true,
  }
