export const microCagedGrupoDicts: {
  [key: string]: string;
} = {
  "A": "AGROPECUÁRIA",
  "B": "INDÚSTRIA",
  "C": "INDÚSTRIA",
  "D": "INDÚSTRIA",
  "E": "INDÚSTRIA",
  "F": "CONSTRUÇÃO",
  "G": "COMÉRCIO",
  "H": "SERVIÇOS",
  "I": "SERVIÇOS",
  "J": "SERVIÇOS",
  "K": "SERVIÇOS",
  "L": "SERVIÇOS",
  "M": "SERVIÇOS",
  "N": "SERVIÇOS",
  "O": "SERVIÇOS",
  "P": "SERVIÇOS",
  "Q": "SERVIÇOS",
  "R": "SERVIÇOS",
  "S": "SERVIÇOS",
  "T": "SERVIÇOS",
  "U": "SERVIÇOS",
  "Z": "NÃO IDENTIFICADO",
};
