export const raisClassesDicts = {
    "01113": "Cultivo de cereais",
    "01121": "Cultivo de algodão herbáceo e de outras fibras de lavoura temporária",
    "01130": "Cultivo de cana-de-açúcar",
    "01148": "Cultivo de fumo",
    "01156": "Cultivo de soja",
    "01164": "Cultivo de oleaginosas de lavoura temporária, exceto soja",
    "01199": "Cultivo de plantas de lavoura temporária não especificadas anteriormente",
    "01211": "Horticultura",
    "01229": "Cultivo de flores e plantas ornamentais",
    "01318": "Cultivo de laranja",
    "01326": "Cultivo de uva",
    "01334": "Cultivo de frutas de lavoura permanente, exceto laranja e uva",
    "01342": "Cultivo de café",
    "01351": "Cultivo de cacau",
    "01393": "Cultivo de plantas de lavoura permanente não especificadas anteriormente",
    "01415": "Produção de sementes certificadas",
    "01423": "Produção de mudas e outras formas de propagação vegetal, certificadas",
    "01512": "Criação de bovinos",
    "01521": "Criação de outros animais de grande porte",
    "01539": "Criação de caprinos e ovinos",
    "01547": "Criação de suínos",
    "01555": "Criação de aves",
    "01598": "Criação de animais não especificados anteriormente",
    "01610": "Atividades de apoio à agricultura",
    "01628": "Atividades de apoio à pecuária",
    "01636": "Atividades de pós-colheita",
    "01709": "Caça e serviços relacionados",
    "02101": "Produção florestal - florestas plantadas",
    "02209": "Produção florestal - florestas nativas",
    "02306": "Atividades de apoio à produção florestal",
    "03116": "Pesca em água salgada",
    "03124": "Pesca em água doce",
    "03213": "Aqüicultura em água salgada e salobra",
    "03221": "Aqüicultura em água doce",
    "05003": "Extração de carvão mineral",
    "06000": "Extração de petróleo e gás natural",
    "07103": "Extração de minério de ferro",
    "07219": "Extração de minério de alumínio",
    "07227": "Extração de minério de estanho",
    "07235": "Extração de minério de manganês",
    "07243": "Extração de minério de metais preciosos",
    "07251": "Extração de minerais radioativos",
    "07294": "Extração de minerais metálicos não-ferrosos não especificados anteriormente",
    "08100": "Extração de pedra, areia e argila",
    "08916": "Extração de minerais para fabricação de adubos, fertilizantes e outros produtos químicos",
    "08924": "Extração e refino de sal marinho e sal-gema",
    "08932": "Extração de gemas (pedras preciosas e semipreciosas)",
    "08991": "Extração de minerais não-metálicos não especificados anteriormente",
    "09106": "Atividades de apoio à extração de petróleo e gás natural",
    "09904": "Atividades de apoio à extração de minerais, exceto petróleo e gás natural",
    "10112": "Abate de reses, exceto suínos",
    "10121": "Abate de suínos, aves e outros pequenos animais",
    "10139": "Fabricação de produtos de carne",
    "10201": "Preservação do pescado e fabricação de produtos do pescado",
    "10317": "Fabricação de conservas de frutas",
    "10325": "Fabricação de conservas de legumes e outros vegetais",
    "10333": "Fabricação de sucos de frutas, hortaliças e legumes",
    "10414": "Fabricação de óleos vegetais em bruto, exceto óleo de milho",
    "10422": "Fabricação de óleos vegetais refinados, exceto óleo de milho",
    "10431": "Fabricação de margarina e outras gorduras vegetais e de óleos não-comestíveis de animais",
    "10511": "Preparação do leite",
    "10520": "Fabricação de laticínios",
    "10538": "Fabricação de sorvetes e outros gelados comestíveis",
    "10619": "Beneficiamento de arroz e fabricação de produtos do arroz",
    "10627": "Moagem de trigo e fabricação de derivados",
    "10635": "Fabricação de farinha de mandioca e derivados",
    "10643": "Fabricação de farinha de milho e derivados, exceto óleos de milho",
    "10651": "Fabricação de amidos e féculas de vegetais e de óleos de milho",
    "10660": "Fabricação de alimentos para animais",
    "10694": "Moagem e fabricação de produtos de origem vegetal não especificados anteriormente",
    "10716": "Fabricação de açúcar em bruto",
    "10724": "Fabricação de açúcar refinado",
    "10813": "Torrefação e moagem de café",
    "10821": "Fabricação de produtos à base de café",
    "10911": "Fabricação de produtos de panificação",
    "10929": "Fabricação de biscoitos e bolachas",
    "10937": "Fabricação de produtos derivados do cacau, de chocolates e confeitos",
    "10945": "Fabricação de massas alimentícias",
    "10953": "Fabricação de especiarias, molhos, temperos e condimentos",
    "10961": "Fabricação de alimentos e pratos prontos",
    "10996": "Fabricação de produtos alimentícios não especificados anteriormente",
    "11119": "Fabricação de aguardentes e outras bebidas destiladas",
    "11127": "Fabricação de vinho",
    "11135": "Fabricação de malte, cervejas e chopes",
    "11216": "Fabricação de águas envasadas",
    "11224": "Fabricação de refrigerantes e de outras bebidas não-alcoólicas",
    "12107": "Processamento industrial do fumo",
    "12204": "Fabricação de produtos do fumo",
    "13111": "Preparação e fiação de fibras de algodão",
    "13120": "Preparação e fiação de fibras têxteis naturais, exceto algodão",
    "13138": "Fiação de fibras artificiais e sintéticas",
    "13146": "Fabricação de linhas para costurar e bordar",
    "13219": "Tecelagem de fios de algodão",
    "13227": "Tecelagem de fios de fibras têxteis naturais, exceto algodão",
    "13235": "Tecelagem de fios de fibras artificiais e sintéticas",
    "13308": "Fabricação de tecidos de malha",
    "13405": "Acabamentos em fios, tecidos e artefatos têxteis",
    "13511": "Fabricação de artefatos têxteis para uso doméstico",
    "13529": "Fabricação de artefatos de tapeçaria",
    "13537": "Fabricação de artefatos de cordoaria",
    "13545": "Fabricação de tecidos especiais, inclusive artefatos",
    "13596": "Fabricação de outros produtos têxteis não especificados anteriormente",
    "14118": "Confecção de roupas íntimas",
    "14126": "Confecção de peças do vestuário, exceto roupas íntimas",
    "14134": "Confecção de roupas profissionais",
    "14142": "Fabricação de acessórios do vestuário, exceto para segurança e proteção",
    "14215": "Fabricação de meias",
    "14223": "Fabricação de artigos do vestuário, produzidos em malharias e tricotagens, exceto meias",
    "15106": "Curtimento e outras preparações de couro",
    "15211": "Fabricação de artigos para viagem, bolsas e semelhantes de qualquer material",
    "15297": "Fabricação de artefatos de couro não especificados anteriormente",
    "15319": "Fabricação de calçados de couro",
    "15327": "Fabricação de tênis de qualquer material",
    "15335": "Fabricação de calçados de material sintético",
    "15394": "Fabricação de calçados de materiais não especificados anteriormente",
    "15408": "Fabricação de partes para calçados, de qualquer material",
    "16102": "Desdobramento de madeira",
    "16218": "Fabricação de madeira laminada e de chapas de madeira compensada, prensada e aglomerada",
    "16226": "Fabricação de estruturas de madeira e de artigos de carpintaria para construção",
    "16234": "Fabricação de artefatos de tanoaria e de embalagens de madeira",
    "16293": "Fabricação de artefatos de madeira, palha, cortiça, vime e material trançado não especificados anteriormente, exceto móveis",
    "17109": "Fabricação de celulose e outras pastas para a fabricação de papel",
    "17214": "Fabricação de papel",
    "17222": "Fabricação de cartolina e papel-cartão",
    "17311": "Fabricação de embalagens de papel",
    "17320": "Fabricação de embalagens de cartolina e papel-cartão",
    "17338": "Fabricação de chapas e de embalagens de papelão ondulado",
    "17419": "Fabricação de produtos de papel, cartolina, papel-cartão e papelão ondulado para uso comercial e de escritório",
    "17427": "Fabricação de produtos de papel para usos doméstico e higiênico-sanitário",
    "17494": "Fabricação de produtos de pastas celulósicas, papel, cartolina, papel-cartão e papelão ondulado não especificados anteriormente",
    "18113": "Impressão de jornais, livros, revistas e outras publicações periódicas",
    "18121": "Impressão de material de segurança",
    "18130": "Impressão de materiais para outros usos",
    "18211": "Serviços de pré-impressão",
    "18229": "Serviços de acabamentos gráficos",
    "18300": "Reprodução de materiais gravados em qualquer suporte",
    "19101": "Coquerias",
    "19217": "Fabricação de produtos do refino de petróleo",
    "19225": "Fabricação de produtos derivados do petróleo, exceto produtos do refino",
    "19314": "Fabricação de álcool",
    "19322": "Fabricação de biocombustíveis, exceto álcool",
    "20118": "Fabricação de cloro e álcalis",
    "20126": "Fabricação de intermediários para fertilizantes",
    "20134": "Fabricação de adubos e fertilizantes",
    "20142": "Fabricação de gases industriais",
    "20193": "Fabricação de produtos químicos inorgânicos não especificados anteriormente",
    "20215": "Fabricação de produtos petroquímicos básicos",
    "20223": "Fabricação de intermediários para plastificantes, resinas e fibras",
    "20291": "Fabricação de produtos químicos orgânicos não especificados anteriormente",
    "20312": "Fabricação de resinas termoplásticas",
    "20321": "Fabricação de resinas termofixas",
    "20339": "Fabricação de elastômeros",
    "20401": "Fabricação de fibras artificiais e sintéticas",
    "20517": "Fabricação de defensivos agrícolas",
    "20525": "Fabricação de desinfestantes domissanitários",
    "20614": "Fabricação de sabões e detergentes sintéticos",
    "20622": "Fabricação de produtos de limpeza e polimento",
    "20631": "Fabricação de cosméticos, produtos de perfumaria e de higiene pessoal",
    "20711": "Fabricação de tintas, vernizes, esmaltes e lacas",
    "20720": "Fabricação de tintas de impressão",
    "20738": "Fabricação de impermeabilizantes, solventes e produtos afins",
    "20916": "Fabricação de adesivos e selantes",
    "20924": "Fabricação de explosivos",
    "20932": "Fabricação de aditivos de uso industrial",
    "20941": "Fabricação de catalisadores",
    "20991": "Fabricação de produtos químicos não especificados anteriormente",
    "21106": "Fabricação de produtos farmoquímicos",
    "21211": "Fabricação de medicamentos para uso humano",
    "21220": "Fabricação de medicamentos para uso veterinário",
    "21238": "Fabricação de preparações farmacêuticas",
    "22111": "Fabricação de pneumáticos e de câmaras-de-ar",
    "22129": "Reforma de pneumáticos usados",
    "22196": "Fabricação de artefatos de borracha não especificados anteriormente",
    "22218": "Fabricação de laminados planos e tubulares de material plástico",
    "22226": "Fabricação de embalagens de material plástico",
    "22234": "Fabricação de tubos e acessórios de material plástico para uso na construção",
    "22293": "Fabricação de artefatos de material plástico não especificados anteriormente",
    "23117": "Fabricação de vidro plano e de segurança",
    "23125": "Fabricação de embalagens de vidro",
    "23192": "Fabricação de artigos de vidro",
    "23206": "Fabricação de cimento",
    "23303": "Fabricação de artefatos de concreto, cimento, fibrocimento, gesso e materiais semelhantes",
    "23419": "Fabricação de produtos cerâmicos refratários",
    "23427": "Fabricação de produtos cerâmicos não-refratários para uso estrutural na construção",
    "23494": "Fabricação de produtos cerâmicos não-refratários não especificados anteriormente",
    "23915": "Aparelhamento e outros trabalhos em pedras",
    "23923": "Fabricação de cal e gesso",
    "23991": "Fabricação de produtos de minerais não-metálicos não especificados anteriormente",
    "24113": "Produção de ferro-gusa",
    "24121": "Produção de ferroligas",
    "24211": "Produção de semi-acabados de aço",
    "24229": "Produção de laminados planos de aço",
    "24237": "Produção de laminados longos de aço",
    "24245": "Produção de relaminados, trefilados e perfilados de aço",
    "24318": "Produção de tubos de aço com costura",
    "24393": "Produção de outros tubos de ferro e aço",
    "24415": "Metalurgia do alumínio e suas ligas",
    "24423": "Metalurgia dos metais preciosos",
    "24431": "Metalurgia do cobre",
    "24491": "Metalurgia dos metais não-ferrosos e suas ligas não especificados anteriormente",
    "24512": "Fundição de ferro e aço",
    "24521": "Fundição de metais não-ferrosos e suas ligas",
    "25110": "Fabricação de estruturas metálicas",
    "25128": "Fabricação de esquadrias de metal",
    "25136": "Fabricação de obras de caldeiraria pesada",
    "25217": "Fabricação de tanques, reservatórios metálicos e caldeiras para aquecimento central",
    "25225": "Fabricação de caldeiras geradoras de vapor, exceto para aquecimento central e para veículos",
    "25314": "Produção de forjados de aço e de metais não-ferrosos e suas ligas",
    "25322": "Produção de artefatos estampados de metal; metalurgia do pó",
    "25390": "Serviços de usinagem, solda, tratamento e revestimento em metais",
    "25411": "Fabricação de artigos de cutelaria",
    "25420": "Fabricação de artigos de serralheria, exceto esquadrias",
    "25438": "Fabricação de ferramentas",
    "25501": "Fabricação de equipamento bélico pesado, armas de fogo e munições",
    "25918": "Fabricação de embalagens metálicas",
    "25926": "Fabricação de produtos de trefilados de metal",
    "25934": "Fabricação de artigos de metal para uso doméstico e pessoal",
    "25993": "Fabricação de produtos de metal não especificados anteriormente",
    "26108": "Fabricação de componentes eletrônicos",
    "26213": "Fabricação de equipamentos de informática",
    "26221": "Fabricação de periféricos para equipamentos de informática",
    "26311": "Fabricação de equipamentos transmissores de comunicação",
    "26329": "Fabricação de aparelhos telefônicos e de outros equipamentos de comunicação",
    "26400": "Fabricação de aparelhos de recepção, reprodução, gravação e amplificação de áudio e vídeo",
    "26515": "Fabricação de aparelhos e equipamentos de medida, teste e controle",
    "26523": "Fabricação de cronômetros e relógios",
    "26604": "Fabricação de aparelhos eletromédicos e eletroterapêuticos e equipamentos de irradiação",
    "26701": "Fabricação de equipamentos e instrumentos ópticos, fotográficos e cinematográficos",
    "26809": "Fabricação de mídias virgens, magnéticas e ópticas",
    "27104": "Fabricação de geradores, transformadores e motores elétricos",
    "27210": "Fabricação de pilhas, baterias e acumuladores elétricos, exceto para veículos automotores",
    "27228": "Fabricação de baterias e acumuladores para veículos automotores",
    "27317": "Fabricação de aparelhos e equipamentos para distribuição e controle de energia elétrica",
    "27325": "Fabricação de material elétrico para instalações em circuito de consumo",
    "27333": "Fabricação de fios, cabos e condutores elétricos isolados",
    "27406": "Fabricação de lâmpadas e outros equipamentos de iluminação",
    "27511": "Fabricação de fogões, refrigeradores e máquinas de lavar e secar para uso doméstico",
    "27597": "Fabricação de aparelhos eletrodomésticos não especificados anteriormente",
    "27902": "Fabricação de equipamentos e aparelhos elétricos não especificados anteriormente",
    "28119": "Fabricação de motores e turbinas, exceto para aviões e veículos rodoviários",
    "28127": "Fabricação de equipamentos hidráulicos e pneumáticos, exceto válvulas",
    "28135": "Fabricação de válvulas, registros e dispositivos semelhantes",
    "28143": "Fabricação de compressores",
    "28151": "Fabricação de equipamentos de transmissão para fins industriais",
    "28216": "Fabricação de aparelhos e equipamentos para instalações térmicas",
    "28224": "Fabricação de máquinas, equipamentos e aparelhos para transporte e elevação de cargas e pessoas",
    "28232": "Fabricação de máquinas e aparelhos de refrigeração e ventilação para uso industrial e comercial",
    "28241": "Fabricação de aparelhos e equipamentos de ar condicionado",
    "28259": "Fabricação de máquinas e equipamentos para saneamento básico e ambiental",
    "28291": "Fabricação de máquinas e equipamentos de uso geral não especificados anteriormente",
    "28313": "Fabricação de tratores agrícolas",
    "28321": "Fabricação de equipamentos para irrigação agrícola",
    "28330": "Fabricação de máquinas e equipamentos para a agricultura e pecuária, exceto para irrigação",
    "28402": "Fabricação de máquinas-ferramenta",
    "28518": "Fabricação de máquinas e equipamentos para a prospecção e extração de petróleo",
    "28526": "Fabricação de outras máquinas e equipamentos para uso na extração mineral, exceto na extração de petróleo",
    "28534": "Fabricação de tratores, exceto agrícolas",
    "28542": "Fabricação de máquinas e equipamentos para terraplenagem, pavimentação e construção, exceto tratores",
    "28615": "Fabricação de máquinas para a indústria metalúrgica, exceto máquinas-ferramenta",
    "28623": "Fabricação de máquinas e equipamentos para as indústrias de alimentos, bebidas e fumo",
    "28631": "Fabricação de máquinas e equipamentos para a indústria têxtil",
    "28640": "Fabricação de máquinas e equipamentos para as indústrias do vestuário, do couro e de calçados",
    "28658": "Fabricação de máquinas e equipamentos para as indústrias de celulose, papel e papelão e artefatos",
    "28666": "Fabricação de máquinas e equipamentos para a indústria do plástico",
    "28691": "Fabricação de máquinas e equipamentos para uso industrial específico não especificados anteriormente",
    "29107": "Fabricação de automóveis, camionetas e utilitários",
    "29204": "Fabricação de caminhões e ônibus",
    "29301": "Fabricação de cabines, carrocerias e reboques para veículos automotores",
    "29417": "Fabricação de peças e acessórios para o sistema motor de veículos automotores",
    "29425": "Fabricação de peças e acessórios para os sistemas de marcha e transmissão de veículos automotores",
    "29433": "Fabricação de peças e acessórios para o sistema de freios de veículos automotores",
    "29441": "Fabricação de peças e acessórios para o sistema de direção e suspensão de veículos automotores",
    "29450": "Fabricação de material elétrico e eletrônico para veículos automotores, exceto baterias",
    "29492": "Fabricação de peças e acessórios para veículos automotores não especificados anteriormente",
    "29506": "Recondicionamento e recuperação de motores para veículos automotores",
    "30113": "Construção de embarcações e estruturas flutuantes",
    "30121": "Construção de embarcações para esporte e lazer",
    "30318": "Fabricação de locomotivas, vagões e outros materiais rodantes",
    "30326": "Fabricação de peças e acessórios para veículos ferroviários",
    "30415": "Fabricação de aeronaves",
    "30423": "Fabricação de turbinas, motores e outros componentes e peças para aeronaves",
    "30504": "Fabricação de veículos militares de combate",
    "30911": "Fabricação de motocicletas",
    "30920": "Fabricação de bicicletas e triciclos não-motorizados",
    "30997": "Fabricação de equipamentos de transporte não especificados anteriormente",
    "31012": "Fabricação de móveis com predominância de madeira",
    "31021": "Fabricação de móveis com predominância de metal",
    "31039": "Fabricação de móveis de outros materiais, exceto madeira e metal",
    "31047": "Fabricação de colchões",
    "32116": "Lapidação de gemas e fabricação de artefatos de ourivesaria e joalheria",
    "32124": "Fabricação de bijuterias e artefatos semelhantes",
    "32205": "Fabricação de instrumentos musicais",
    "32302": "Fabricação de artefatos para pesca e esporte",
    "32400": "Fabricação de brinquedos e jogos recreativos",
    "32507": "Fabricação de instrumentos e materiais para uso médico e odontológico e de artigos ópticos",
    "32914": "Fabricação de escovas, pincéis e vassouras",
    "32922": "Fabricação de equipamentos e acessórios para segurança e proteção pessoal e profissional",
    "32990": "Fabricação de produtos diversos não especificados anteriormente",
    "33112": "Manutenção e reparação de tanques, reservatórios metálicos e caldeiras, exceto para veículos",
    "33121": "Manutenção e reparação de equipamentos eletrônicos e ópticos",
    "33139": "Manutenção e reparação de máquinas e equipamentos elétricos",
    "33147": "Manutenção e reparação de máquinas e equipamentos da indústria mecânica",
    "33155": "Manutenção e reparação de veículos ferroviários",
    "33163": "Manutenção e reparação de aeronaves",
    "33171": "Manutenção e reparação de embarcações",
    "33198": "Manutenção e reparação de equipamentos e produtos não especificados anteriormente",
    "33210": "Instalação de máquinas e equipamentos industriais",
    "33295": "Instalação de equipamentos não especificados anteriormente",
    "35115": "Geração de energia elétrica",
    "35123": "Transmissão de energia elétrica",
    "35131": "Comércio atacadista de energia elétrica",
    "35140": "Distribuição de energia elétrica",
    "35204": "Produção de gás; processamento de gás natural; distribuição de combustíveis gasosos por redes urbanas",
    "35301": "Produção e distribuição de vapor, água quente e ar condicionado",
    "36006": "Captação, tratamento e distribuição de água",
    "37011": "Gestão de redes de esgoto",
    "37029": "Atividades relacionadas a esgoto, exceto a gestão de redes",
    "38114": "Coleta de resíduos não-perigosos",
    "38122": "Coleta de resíduos perigosos",
    "38211": "Tratamento e disposição de resíduos não-perigosos",
    "38220": "Tratamento e disposição de resíduos perigosos",
    "38319": "Recuperação de materiais metálicos",
    "38327": "Recuperação de materiais plásticos",
    "38394": "Recuperação de materiais não especificados anteriormente",
    "39005": "Descontaminação e outros serviços de gestão de resíduos",
    "41107": "Incorporação de empreendimentos imobiliários",
    "41204": "Construção de edifícios",
    "42111": "Construção de rodovias e ferrovias",
    "42120": "Construção de obras-de-arte especiais",
    "42138": "Obras de urbanização - ruas, praças e calçadas",
    "42219": "Obras para geração e distribuição de energia elétrica e para telecomunicações",
    "42227": "Construção de redes de abastecimento de água, coleta de esgoto e construções correlatas",
    "42235": "Construção de redes de transportes por dutos, exceto para água e esgoto",
    "42910": "Obras portuárias, marítimas e fluviais",
    "42928": "Montagem de instalações industriais e de estruturas metálicas",
    "42995": "Obras de engenharia civil não especificadas anteriormente",
    "43118": "Demolição e preparação de canteiros de obras",
    "43126": "Perfurações e sondagens",
    "43134": "Obras de terraplenagem",
    "43193": "Serviços de preparação do terreno não especificados anteriormente",
    "43215": "Instalações elétricas",
    "43223": "Instalações hidráulicas, de sistemas de ventilação e refrigeração",
    "43291": "Obras de instalações em construções não especificadas anteriormente",
    "43304": "Obras de acabamento",
    "43916": "Obras de fundações",
    "43991": "Serviços especializados para construção não especificados anteriormente",
    "45111": "Comércio a varejo e por atacado de veículos automotores",
    "45129": "Representantes comerciais e agentes do comércio de veículos automotores",
    "45200": "Manutenção e reparação de veículos automotores",
    "45307": "Comércio de peças e acessórios para veículos automotores",
    "45412": "Comércio por atacado e a varejo de motocicletas, peças e acessórios",
    "45421": "Representantes comerciais e agentes do comércio de motocicletas, peças e acessórios",
    "45439": "Manutenção e reparação de motocicletas",
    "46117": "Representantes comerciais e agentes do comércio de matérias-primas agrícolas e animais vivos",
    "46125": "Representantes comerciais e agentes do comércio de combustíveis, minerais, produtos siderúrgicos e químicos",
    "46133": "Representantes comerciais e agentes do comércio de madeira, material de construção e ferragens",
    "46141": "Representantes comerciais e agentes do comércio de máquinas, equipamentos, embarcações e aeronaves",
    "46150": "Representantes comerciais e agentes do comércio de eletrodomésticos, móveis e artigos de uso doméstico",
    "46168": "Representantes comerciais e agentes do comércio de têxteis, vestuário, calçados e artigos de viagem",
    "46176": "Representantes comerciais e agentes do comércio de produtos alimentícios, bebidas e fumo",
    "46184": "Representantes comerciais e agentes do comércio especializado em produtos não especificados anteriormente",
    "46192": "Representantes comerciais e agentes do comércio de mercadorias em geral não especializado",
    "46214": "Comércio atacadista de café em grão",
    "46222": "Comércio atacadista de soja",
    "46231": "Comércio atacadista de animais vivos, alimentos para animais e matérias-primas agrícolas, exceto café e soja",
    "46311": "Comércio atacadista de leite e laticínios",
    "46320": "Comércio atacadista de cereais e leguminosas beneficiados, farinhas, amidos e féculas",
    "46338": "Comércio atacadista de hortifrutigranjeiros",
    "46346": "Comércio atacadista de carnes, produtos da carne e pescado",
    "46354": "Comércio atacadista de bebidas",
    "46362": "Comércio atacadista de produtos do fumo",
    "46371": "Comércio atacadista especializado em produtos alimentícios não especificados anteriormente",
    "46397": "Comércio atacadista de produtos alimentícios em geral",
    "46419": "Comércio atacadista de tecidos, artefatos de tecidos e de armarinho",
    "46427": "Comércio atacadista de artigos do vestuário e acessórios",
    "46435": "Comércio atacadista de calçados e artigos de viagem",
    "46443": "Comércio atacadista de produtos farmacêuticos para uso humano e veterinário",
    "46451": "Comércio atacadista de instrumentos e materiais para uso médico, cirúrgico, ortopédico e odontológico",
    "46460": "Comércio atacadista de cosméticos, produtos de perfumaria e de higiene pessoal",
    "46478": "Comércio atacadista de artigos de escritório e de papelaria; livros, jornais e outras publicações",
    "46494": "Comércio atacadista de equipamentos e artigos de uso pessoal e doméstico não especificados anteriormente",
    "46516": "Comércio atacadista de computadores, periféricos e suprimentos de informática",
    "46524": "Comércio atacadista de componentes eletrônicos e equipamentos de telefonia e comunicação",
    "46613": "Comércio atacadista de máquinas, aparelhos e equipamentos para uso agropecuário; partes e peças",
    "46621": "Comércio atacadista de máquinas, equipamentos para terraplenagem, mineração e construção; partes e peças",
    "46630": "Comércio atacadista de máquinas e equipamentos para uso industrial; partes e peças",
    "46648": "Comércio atacadista de máquinas, aparelhos e equipamentos para uso odonto-médico-hospitalar; partes e peças",
    "46656": "Comércio atacadista de máquinas e equipamentos para uso comercial; partes e peças",
    "46699": "Comércio atacadista de máquinas, aparelhos e equipamentos não especificados anteriormente; partes e peças",
    "46711": "Comércio atacadista de madeira e produtos derivados",
    "46729": "Comércio atacadista de ferragens e ferramentas",
    "46737": "Comércio atacadista de material elétrico",
    "46745": "Comércio atacadista de cimento",
    "46796": "Comércio atacadista especializado de materiais de construção não especificados anteriormente e de materiais de construção em geral",
    "46818": "Comércio atacadista de combustíveis sólidos, líquidos e gasosos, exceto gás natural e GLP",
    "46826": "Comércio atacadista de gás liqüefeito de petróleo (GLP)",
    "46834": "Comércio atacadista de defensivos agrícolas, adubos, fertilizantes e corretivos do solo",
    "46842": "Comércio atacadista de produtos químicos e petroquímicos, exceto agroquímicos",
    "46851": "Comércio atacadista de produtos siderúrgicos e metalúrgicos, exceto para construção",
    "46869": "Comércio atacadista de papel e papelão em bruto e de embalagens",
    "46877": "Comércio atacadista de resíduos e sucatas",
    "46893": "Comércio atacadista especializado de outros produtos intermediários não especificados anteriormente",
    "46915": "Comércio atacadista de mercadorias em geral, com predominância de produtos alimentícios",
    "46923": "Comércio atacadista de mercadorias em geral, com predominância de insumos agropecuários",
    "46931": "Comércio atacadista de mercadorias em geral, sem predominância de alimentos ou de insumos agropecuários",
    "47113": "Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - hipermercados e supermercados",
    "47121": "Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - minimercados, mercearias e armazéns",
    "47130": "Comércio varejista de mercadorias em geral, sem predominância de produtos alimentícios",
    "47211": "Comércio varejista de produtos de padaria, laticínio, doces, balas e semelhantes",
    "47229": "Comércio varejista de carnes e pescados - açougues e peixarias",
    "47237": "Comércio varejista de bebidas",
    "47245": "Comércio varejista de hortifrutigranjeiros",
    "47296": "Comércio varejista de produtos alimentícios em geral ou especializado em produtos alimentícios não especificados anteriormente; produtos do fumo",
    "47318": "Comércio varejista de combustíveis para veículos automotores",
    "47326": "Comércio varejista de lubrificantes",
    "47415": "Comércio varejista de tintas e materiais para pintura",
    "47423": "Comércio varejista de material elétrico",
    "47431": "Comércio varejista de vidros",
    "47440": "Comércio varejista de ferragens, madeira e materiais de construção",
    "47512": "Comércio varejista especializado de equipamentos e suprimentos de informática",
    "47521": "Comércio varejista especializado de equipamentos de telefonia e comunicação",
    "47539": "Comércio varejista especializado de eletrodomésticos e equipamentos de áudio e vídeo",
    "47547": "Comércio varejista especializado de móveis, colchoaria e artigos de iluminação",
    "47555": "Comércio varejista especializado de tecidos e artigos de cama, mesa e banho",
    "47563": "Comércio varejista especializado de instrumentos musicais e acessórios",
    "47571": "Comércio varejista especializado de peças e acessórios para aparelhos eletroeletrônicos para uso doméstico, exceto informática e comunicação",
    "47598": "Comércio varejista de artigos de uso doméstico não especificados anteriormente",
    "47610": "Comércio varejista de livros, jornais, revistas e papelaria",
    "47628": "Comércio varejista de discos, CDs, DVDs e fitas",
    "47636": "Comércio varejista de artigos recreativos e esportivos",
    "47717": "Comércio varejista de produtos farmacêuticos para uso humano e veterinário",
    "47725": "Comércio varejista de cosméticos, produtos de perfumaria e de higiene pessoal",
    "47733": "Comércio varejista de artigos médicos e ortopédicos",
    "47741": "Comércio varejista de artigos de óptica",
    "47814": "Comércio varejista de artigos do vestuário e acessórios",
    "47822": "Comércio varejista de calçados e artigos de viagem",
    "47831": "Comércio varejista de jóias e relógios",
    "47849": "Comércio varejista de gás liqüefeito de petróleo (GLP)",
    "47857": "Comércio varejista de artigos usados",
    "47890": "Comércio varejista de outros produtos novos não especificados anteriormente",
    "47903": "Comércio ambulante e outros tipos de comércio varejista",
    "49116": "Transporte ferroviário de carga",
    "49124": "Transporte metroferroviário de passageiros",
    "49213": "Transporte rodoviário coletivo de passageiros, com itinerário fixo, municipal e em região metropolitana",
    "49221": "Transporte rodoviário coletivo de passageiros, com itinerário fixo, intermunicipal, interestadual e internacional",
    "49230": "Transporte rodoviário de táxi",
    "49248": "Transporte escolar",
    "49299": "Transporte rodoviário coletivo de passageiros, sob regime de fretamento, e outros transportes rodoviários não especificados anteriormente",
    "49302": "Transporte rodoviário de carga",
    "49400": "Transporte dutoviário",
    "49507": "Trens turísticos, teleféricos e similares",
    "50114": "Transporte marítimo de cabotagem",
    "50122": "Transporte marítimo de longo curso",
    "50211": "Transporte por navegação interior de carga",
    "50220": "Transporte por navegação interior de passageiros em linhas regulares",
    "50301": "Navegação de apoio",
    "50912": "Transporte por navegação de travessia",
    "50998": "Transportes aquaviários não especificados anteriormente",
    "51111": "Transporte aéreo de passageiros regular",
    "51129": "Transporte aéreo de passageiros não-regular",
    "51200": "Transporte aéreo de carga",
    "51307": "Transporte espacial",
    "52117": "Armazenamento",
    "52125": "Carga e descarga",
    "52214": "Concessionárias de rodovias, pontes, túneis e serviços relacionados",
    "52222": "Terminais rodoviários e ferroviários",
    "52231": "Estacionamento de veículos",
    "52290": "Atividades auxiliares dos transportes terrestres não especificadas anteriormente",
    "52311": "Gestão de portos e terminais",
    "52320": "Atividades de agenciamento marítimo",
    "52397": "Atividades auxiliares dos transportes aquaviários não especificadas anteriormente",
    "52401": "Atividades auxiliares dos transportes aéreos",
    "52508": "Atividades relacionadas à organização do transporte de carga",
    "53105": "Atividades de Correio",
    "53202": "Atividades de malote e de entrega",
    "55108": "Hotéis e similares",
    "55906": "Outros tipos de alojamento não especificados anteriormente",
    "56112": "Restaurantes e outros estabelecimentos de serviços de alimentação e bebidas",
    "56121": "Serviços ambulantes de alimentação",
    "56201": "Serviços de catering, bufê e outros serviços de comida preparada",
    "58115": "Edição de livros",
    "58123": "Edição de jornais",
    "58131": "Edição de revistas",
    "58191": "Edição de cadastros, listas e outros produtos gráficos",
    "58212": "Edição integrada à impressão de livros",
    "58221": "Edição integrada à impressão de jornais",
    "58239": "Edição integrada à impressão de revistas",
    "58298": "Edição integrada à impressão de cadastros, listas e outros produtos gráficos",
    "59111": "Atividades de produção cinematográfica, de vídeos e de programas de televisão",
    "59120": "Atividades de pós-produção cinematográfica, de vídeos e de programas de televisão",
    "59138": "Distribuição cinematográfica, de vídeo e de programas de televisão",
    "59146": "Atividades de exibição cinematográfica",
    "59201": "Atividades de gravação de som e de edição de música",
    "60101": "Atividades de rádio",
    "60217": "Atividades de televisão aberta",
    "60225": "Programadoras e atividades relacionadas à televisão por assinatura",
    "61108": "Telecomunicações por fio",
    "61205": "Telecomunicações sem fio",
    "61302": "Telecomunicações por satélite",
    "61418": "Operadoras de televisão por assinatura por cabo",
    "61426": "Operadoras de televisão por assinatura por microondas",
    "61434": "Operadoras de televisão por assinatura por satélite",
    "61906": "Outras atividades de telecomunicações",
    "62015": "Desenvolvimento de programas de computador sob encomenda",
    "62023": "Desenvolvimento e licenciamento de programas de computador customizáveis",
    "62031": "Desenvolvimento e licenciamento de programas de computador não-customizáveis",
    "62040": "Consultoria em tecnologia da informação",
    "62091": "Suporte técnico, manutenção e outros serviços em tecnologia da informação",
    "63119": "Tratamento de dados, provedores de serviços de aplicação e serviços de hospedagem na internet",
    "63194": "Portais, provedores de conteúdo e outros serviços de informação na internet",
    "63917": "Agências de notícias",
    "63992": "Outras atividades de prestação de serviços de informação não especificadas anteriormente",
    "64107": "Banco Central",
    "64212": "Bancos comerciais",
    "64221": "Bancos múltiplos, com carteira comercial",
    "64239": "Caixas econômicas",
    "64247": "Crédito cooperativo",
    "64310": "Bancos múltiplos, sem carteira comercial",
    "64328": "Bancos de investimento",
    "64336": "Bancos de desenvolvimento",
    "64344": "Agências de fomento",
    "64352": "Crédito imobiliário",
    "64361": "Sociedades de crédito, financiamento e investimento - financeiras",
    "64379": "Sociedades de crédito ao microempreendedor",
    "64387": "Bancos de câmbio e outras instituições de intermediação não-monetária",
    "64409": "Arrendamento mercantil",
    "64506": "Sociedades de capitalização",
    "64611": "Holdings de instituições financeiras",
    "64620": "Holdings de instituições não-financeiras",
    "64638": "Outras sociedades de participação, exceto holdings",
    "64701": "Fundos de investimento",
    "64913": "Sociedades de fomento mercantil - factoring",
    "64921": "Securitização de créditos",
    "64930": "Administração de consórcios para aquisição de bens e direitos",
    "64999": "Outras atividades de serviços financeiros não especificadas anteriormente",
    "65111": "Seguros de vida",
    "65120": "Seguros não-vida",
    "65201": "Seguros-saúde",
    "65308": "Resseguros",
    "65413": "Previdência complementar fechada",
    "65421": "Previdência complementar aberta",
    "65502": "Planos de saúde",
    "66118": "Administração de bolsas e mercados de balcão organizados",
    "66126": "Atividades de intermediários em transações de títulos, valores mobiliários e mercadorias",
    "66134": "Administração de cartões de crédito",
    "66193": "Atividades auxiliares dos serviços financeiros não especificadas anteriormente",
    "66215": "Avaliação de riscos e perdas",
    "66223": "Corretores e agentes de seguros, de planos de previdência complementar e de saúde",
    "66291": "Atividades auxiliares dos seguros, da previdência complementar e dos planos de saúde não especificadas anteriormente",
    "66304": "Atividades de administração de fundos por contrato ou comissão",
    "68102": "Atividades imobiliárias de imóveis próprios",
    "68218": "Intermediação na compra, venda e aluguel de imóveis",
    "68226": "Gestão e administração da propriedade imobiliária",
    "69117": "Atividades jurídicas, exceto cartórios",
    "69125": "Cartórios",
    "69206": "Atividades de contabilidade, consultoria e auditoria contábil e tributária",
    "70107": "Sedes de empresas e unidades administrativas locais",
    "70204": "Atividades de consultoria em gestão empresarial",
    "71111": "Serviços de arquitetura",
    "71120": "Serviços de engenharia",
    "71197": "Atividades técnicas relacionadas à arquitetura e engenharia",
    "71201": "Testes e análises técnicas",
    "72100": "Pesquisa e desenvolvimento experimental em ciências físicas e naturais",
    "72207": "Pesquisa e desenvolvimento experimental em ciências sociais e humanas",
    "73114": "Agências de publicidade",
    "73122": "Agenciamento de espaços para publicidade, exceto em veículos de comunicação",
    "73190": "Atividades de publicidade não especificadas anteriormente",
    "73203": "Pesquisas de mercado e de opinião pública",
    "74102": "Design e decoração de interiores",
    "74200": "Atividades fotográficas e similares",
    "74901": "Atividades profissionais, científicas e técnicas não especificadas anteriormente",
    "75001": "Atividades veterinárias",
    "77110": "Locação de automóveis sem condutor",
    "77195": "Locação de meios de transporte, exceto automóveis, sem condutor",
    "77217": "Aluguel de equipamentos recreativos e esportivos",
    "77225": "Aluguel de fitas de vídeo, DVDs e similares",
    "77233": "Aluguel de objetos do vestuário, jóias e acessórios",
    "77292": "Aluguel de objetos pessoais e domésticos não especificados anteriormente",
    "77314": "Aluguel de máquinas e equipamentos agrícolas sem operador",
    "77322": "Aluguel de máquinas e equipamentos para construção sem operador",
    "77331": "Aluguel de máquinas e equipamentos para escritório",
    "77390": "Aluguel de máquinas e equipamentos não especificados anteriormente",
    "77403": "Gestão de ativos intangíveis não-financeiros",
    "78108": "Seleção e agenciamento de mão-de-obra",
    "78205": "Locação de mão-de-obra temporária",
    "78302": "Fornecimento e gestão de recursos humanos para terceiros",
    "79112": "Agências de viagens",
    "79121": "Operadores turísticos",
    "79902": "Serviços de reservas e outros serviços de turismo não especificados anteriormente",
    "80111": "Atividades de vigilância e segurança privada",
    "80129": "Atividades de transporte de valores",
    "80200": "Atividades de monitoramento de sistemas de segurança",
    "80307": "Atividades de investigação particular",
    "81117": "Serviços combinados para apoio a edifícios, exceto condomínios prediais",
    "81125": "Condomínios prediais",
    "81214": "Limpeza em prédios e em domicílios",
    "81222": "Imunização e controle de pragas urbanas",
    "81290": "Atividades de limpeza não especificadas anteriormente",
    "81303": "Atividades paisagísticas",
    "82113": "Serviços combinados de escritório e apoio administrativo",
    "82199": "Fotocópias, preparação de documentos e outros serviços especializados de apoio administrativo",
    "82202": "Atividades de teleatendimento",
    "82300": "Atividades de organização de eventos, exceto culturais e esportivos",
    "82911": "Atividades de cobrança e informações cadastrais",
    "82920": "Envasamento e empacotamento sob contrato",
    "82997": "Atividades de serviços prestados principalmente às empresas não especificadas anteriormente",
    "84116": "Administração pública em geral",
    "84124": "Regulação das atividades de saúde, educação, serviços culturais e outros serviços sociais",
    "84132": "Regulação das atividades econômicas",
    "84213": "Relações exteriores",
    "84221": "Defesa",
    "84230": "Justiça",
    "84248": "Segurança e ordem pública",
    "84256": "Defesa Civil",
    "84302": "Seguridade social obrigatória",
    "85112": "Educação infantil - creche",
    "85121": "Educação infantil - pré-escola",
    "85139": "Ensino fundamental",
    "85201": "Ensino médio",
    "85317": "Educação superior - graduação",
    "85325": "Educação superior - graduação e pós-graduação",
    "85333": "Educação superior - pós-graduação e extensão",
    "85414": "Educação profissional de nível técnico",
    "85422": "Educação profissional de nível tecnológico",
    "85503": "Atividades de apoio à educação",
    "85911": "Ensino de esportes",
    "85929": "Ensino de arte e cultura",
    "85937": "Ensino de idiomas",
    "85996": "Atividades de ensino não especificadas anteriormente",
    "86101": "Atividades de atendimento hospitalar",
    "86216": "Serviços móveis de atendimento a urgências",
    "86224": "Serviços de remoção de pacientes, exceto os serviços móveis de atendimento a urgências",
    "86305": "Atividades de atenção ambulatorial executadas por médicos e odontólogos",
    "86402": "Atividades de serviços de complementação diagnóstica e terapêutica",
    "86500": "Atividades de profissionais da área de saúde, exceto médicos e odontólogos",
    "86607": "Atividades de apoio à gestão de saúde",
    "86909": "Atividades de atenção à saúde humana não especificadas anteriormente",
    "87115": "Atividades de assistência a idosos, deficientes físicos, imunodeprimidos e convalescentes prestadas em residências coletivas e particulares",
    "87123": "Atividades de fornecimento de infra-estrutura de apoio e assistência a paciente no domicílio",
    "87204": "Atividades de assistência psicossocial e à saúde a portadores de distúrbios psíquicos, deficiência mental e dependência química",
    "87301": "Atividades de assistência social prestadas em residências coletivas e particulares",
    "88006": "Serviços de assistência social sem alojamento",
    "90019": "Artes cênicas, espetáculos e atividades complementares",
    "90027": "Criação artística",
    "90035": "Gestão de espaços para artes cênicas, espetáculos e outras atividades artísticas",
    "91015": "Atividades de bibliotecas e arquivos",
    "91023": "Atividades de museus e de exploração, restauração artística e conservação de lugares e prédios históricos e atrações similares",
    "91031": "Atividades de jardins botânicos, zoológicos, parques nacionais, reservas ecológicas e áreas de proteção ambiental",
    "92003": "Atividades de exploração de jogos de azar e apostas",
    "93115": "Gestão de instalações de esportes",
    "93123": "Clubes sociais, esportivos e similares",
    "93131": "Atividades de condicionamento físico",
    "93191": "Atividades esportivas não especificadas anteriormente",
    "93212": "Parques de diversão e parques temáticos",
    "93298": "Atividades de recreação e lazer não especificadas anteriormente",
    "94111": "Atividades de organizações associativas patronais e empresariais",
    "94120": "Atividades de organizações associativas profissionais",
    "94201": "Atividades de organizações sindicais",
    "94308": "Atividades de associações de defesa de direitos sociais",
    "94910": "Atividades de organizações religiosas",
    "94928": "Atividades de organizações políticas",
    "94936": "Atividades de organizações associativas ligadas à cultura e à arte",
    "94995": "Atividades associativas não especificadas anteriormente",
    "95118": "Reparação e manutenção de computadores e de equipamentos periféricos",
    "95126": "Reparação e manutenção de equipamentos de comunicação",
    "95215": "Reparação e manutenção de equipamentos eletroeletrônicos de uso pessoal e doméstico",
    "95291": "Reparação e manutenção de objetos e equipamentos pessoais e domésticos não especificados anteriormente",
    "96017": "Lavanderias, tinturarias e toalheiros",
    "96025": "Cabeleireiros e outras atividades de tratamento de beleza",
    "96033": "Atividades funerárias e serviços relacionados",
    "96092": "Atividades de serviços pessoais não especificadas anteriormente",
    "97005": "Serviços domésticos",
    "99008": "Organismos internacionais e outras instituições extraterritoriais",
  };