type RaisGrupoDicts = {
  [key: string]: string;
};

export const raisGrupoDicts: RaisGrupoDicts = {
    "011": "Produção de lavouras temporárias",
    "012": "Horticultura e floricultura",
    "013": "Produção de lavouras permanentes",
    "014": "Produção de sementes e mudas certificadas",
    "015": "Pecuária",
    "016": "Atividades de apoio à agricultura e à pecuária; atividades de pós-colheita",
    "017": "Caça e serviços relacionados",
    "021": "Produção florestal - florestas plantadas",
    "022": "Produção florestal - florestas nativas",
    "023": "Atividades de apoio à produção florestal",
    "031": "Pesca",
    "032": "Aqüicultura",
    "050": "Extração de carvão mineral",
    "060": "Extração de petróleo e gás natural",
    "071": "Extração de minério de ferro",
    "072": "Extração de minerais metálicos não-ferrosos",
    "081": "Extração de pedra, areia e argila",
    "089": "Extração de outros minerais não-metálicos",
    "091": "Atividades de apoio à extração de petróleo e gás natural",
    "099": "Atividades de apoio à extração de minerais, exceto petróleo e gás natural",
    "101": "Abate e fabricação de produtos de carne",
    "102": "Preservação do pescado e fabricação de produtos do pescado",
    "103": "Fabricação de conservas de frutas, legumes e outros vegetais",
    "104": "Fabricação de óleos e gorduras vegetais e animais",
    "105": "Laticínios",
    "106": "Moagem, fabricação de produtos amiláceos e de alimentos para animais",
    "107": "Fabricação e refino de açúcar",
    "108": "Torrefação e moagem de café",
    "109": "Fabricação de outros produtos alimentícios",
    "111": "Fabricação de bebidas alcoólicas",
    "112": "Fabricação de bebidas não-alcoólicas",
    "121": "Processamento industrial do fumo",
    "122": "Fabricação de produtos do fumo",
    "131": "Preparação e fiação de fibras têxteis",
    "132": "Tecelagem, exceto malha",
    "133": "Fabricação de tecidos de malha",
    "134": "Acabamentos em fios, tecidos e artefatos têxteis",
    "135": "Fabricação de artefatos têxteis, exceto vestuário",
    "141": "Confecção de artigos do vestuário e acessórios",
    "142": "Fabricação de artigos de malharia e tricotagem",
    "151": "Curtimento e outras preparações de couro",
    "152": "Fabricação de artigos para viagem e de artefatos diversos de couro",
    "153": "Fabricação de calçados",
    "154": "Fabricação de partes para calçados, de qualquer material",
    "161": "Desdobramento de madeira",
    "162": "Fabricação de produtos de madeira, cortiça e material trançado, exceto móveis",
    "171": "Fabricação de celulose e outras pastas para a fabricação de papel",
    "172": "Fabricação de papel, cartolina e papel-cartão",
    "173": "Fabricação de embalagens de papel, cartolina, papel-cartão e papelão ondulado",
    "174": "Fabricação de produtos diversos de papel, cartolina, papel-cartão e papelão ondulado",
    "181": "Atividade de impressão",
    "182": "Serviços de pré-impressão e acabamentos gráficos",
    "183": "Reprodução de materiais gravados em qualquer suporte",
    "191": "Coquerias",
    "192": "Fabricação de produtos derivados do petróleo",
    "193": "Fabricação de biocombustíveis",
    "201": "Fabricação de produtos químicos inorgânicos",
    "202": "Fabricação de produtos químicos orgânicos",
    "203": "Fabricação de resinas e elastômeros",
    "204": "Fabricação de fibras artificiais e sintéticas",
    "205": "Fabricação de defensivos agrícolas e desinfestantes domissanitários",
    "206": "Fabricação de sabões, detergentes, produtos de limpeza, cosméticos, produtos de perfumaria e de higiene pessoal",
    "207": "Fabricação de tintas, vernizes, esmaltes, lacas e produtos afins",
    "209": "Fabricação de produtos e preparados químicos diversos",
    "211": "Fabricação de produtos farmoquímicos",
    "212": "Fabricação de produtos farmacêuticos",
    "221": "Fabricação de produtos de borracha",
    "222": "Fabricação de produtos de material plástico",
    "231": "Fabricação de vidro e de produtos do vidro",
    "232": "Fabricação de cimento",
    "233": "Fabricação de artefatos de concreto, cimento, fibrocimento, gesso e materiais semelhantes",
    "234": "Fabricação de produtos cerâmicos",
    "239": "Aparelhamento de pedras e fabricação de outros produtos de minerais não-metálicos",
    "241": "Produção de ferro-gusa e de ferroligas",
    "242": "Siderurgia",
    "243": "Produção de tubos de aço, exceto tubos sem costura",
    "244": "Metalurgia dos metais não-ferrosos",
    "245": "Fundição",
    "251": "Fabricação de estruturas metálicas e obras de caldeiraria pesada",
    "252": "Fabricação de tanques, reservatórios metálicos e caldeiras",
    "253": "Forjaria, estamparia, metalurgia do pó e serviços de tratamento de metais",
    "254": "Fabricação de artigos de cutelaria, de serralheria e ferramentas",
    "255": "Fabricação de equipamento bélico pesado, armas de fogo e munições",
    "259": "Fabricação de produtos de metal não especificados anteriormente",
    "261": "Fabricação de componentes eletrônicos",
    "262": "Fabricação de equipamentos de informática e periféricos",
    "263": "Fabricação de equipamentos de comunicação",
    "264": "Fabricação de aparelhos de recepção, reprodução, gravação e amplificação de áudio e vídeo",
    "265": "Fabricação de aparelhos e instrumentos de medida, teste e controle; cronômetros e relógios",
    "266": "Fabricação de aparelhos eletromédicos e eletroterapêuticos e equipamentos de irradiação",
    "267": "Fabricação de equipamentos e instrumentos ópticos, fotográficos e cinematográficos",
    "268": "Fabricação de mídias virgens, magnéticas e ópticas",
    "271": "Fabricação de geradores, transformadores e motores elétricos",
    "272": "Fabricação de pilhas, baterias e acumuladores elétricos",
    "273": "Fabricação de equipamentos para distribuição e controle de energia elétrica",
    "274": "Fabricação de lâmpadas e outros equipamentos de iluminação",
    "275": "Fabricação de eletrodomésticos",
    "279": "Fabricação de equipamentos e aparelhos elétricos não especificados anteriormente",
    "281": "Fabricação de motores, bombas, compressores e equipamentos de transmissão",
    "282": "Fabricação de máquinas e equipamentos de uso geral",
    "283": "Fabricação de tratores e de máquinas e equipamentos para a agricultura e pecuária",
    "284": "Fabricação de máquinas-ferramenta",
    "285": "Fabricação de máquinas e equipamentos de uso na extração mineral e na construção",
    "286": "Fabricação de máquinas e equipamentos de uso industrial específico",
    "291": "Fabricação de automóveis, camionetas e utilitários",
    "292": "Fabricação de caminhões e ônibus",
    "293": "Fabricação de cabines, carrocerias e reboques para veículos automotores",
    "294": "Fabricação de peças e acessórios para veículos automotores",
    "295": "Recondicionamento e recuperação de motores para veículos automotores",
    "301": "Construção de embarcações",
    "303": "Fabricação de veículos ferroviários",
    "304": "Fabricação de aeronaves",
    "305": "Fabricação de veículos militares de combate",
    "309": "Fabricação de equipamentos de transporte não especificados anteriormente",
    "310": "Fabricação de móveis",
    "321": "Fabricação de artigos de joalheria, bijuteria e semelhantes",
    "322": "Fabricação de instrumentos musicais",
    "323": "Fabricação de artefatos para pesca e esporte",
    "324": "Fabricação de brinquedos e jogos recreativos",
    "325": "Fabricação de instrumentos e materiais para uso médico e odontológico e de artigos ópticos",
    "329": "Fabricação de produtos diversos",
    "331": "Manutenção e reparação de máquinas e equipamentos",
    "332": "Instalação de máquinas e equipamentos",
    "351": "Geração, transmissão e distribuição de energia elétrica",
    "352": "Produção e distribuição de combustíveis gasosos por redes urbanas",
    "353": "Produção e distribuição de vapor, água quente e ar condicionado",
    "360": "Captação, tratamento e distribuição de água",
    "370": "Esgoto e atividades relacionadas",
    "381": "Coleta de resíduos",
    "382": "Tratamento e disposição de resíduos",
    "383": "Recuperação de materiais",
    "390": "Descontaminação e outros serviços de gestão de resíduos",
    "411": "Incorporação de empreendimentos imobiliários",
    "412": "Construção de edifícios",
    "421": "Construção de rodovias, ferrovias, obras urbanas e obras-de-arte especiais",
    "422": "Obras de infra-estrutura para energia elétrica, telecomunicações, água, esgoto e transporte por dutos",
    "429": "Construção de outras obras de infra-estrutura",
    "431": "Demolição e preparação do terreno",
    "432": "Instalações elétricas, hidráulicas e outras instalações em construções",
    "433": "Obras de acabamento",
    "439": "Outros serviços especializados para construção",
    "451": "Comércio de veículos automotores",
    "452": "Manutenção e reparação de veículos automotores",
    "453": "Comércio de peças e acessórios para veículos automotores",
    "454": "Comércio, manutenção e reparação de motocicletas, peças e acessórios",
    "461": "Representantes comerciais e agentes do comércio, exceto de veículos automotores e motocicletas",
    "462": "Comércio atacadista de matérias-primas agrícolas e animais vivos",
    "463": "Comércio atacadista especializado em produtos alimentícios, bebidas e fumo",
    "464": "Comércio atacadista de produtos de consumo não-alimentar",
    "465": "Comércio atacadista de equipamentos e produtos de tecnologias de informação e comunicação",
    "466": "Comércio atacadista de máquinas, aparelhos e equipamentos, exceto de tecnologias de informação e comunicação",
    "467": "Comércio atacadista de madeira, ferragens, ferramentas, material elétrico e material de construção",
    "468": "Comércio atacadista especializado em outros produtos",
    "469": "Comércio atacadista não-especializado",
    "471": "Comércio varejista não-especializado",
    "472": "Comércio varejista de produtos alimentícios, bebidas e fumo",
    "473": "Comércio varejista de combustíveis para veículos automotores",
    "474": "Comércio varejista de material de construção",
    "475": "Comércio varejista de equipamentos de informática e comunicação; equipamentos e artigos de uso doméstico",
    "476": "Comércio varejista de artigos culturais, recreativos e esportivos",
    "477": "Comércio varejista de produtos farmacêuticos, perfumaria e cosméticos e artigos médicos, ópticos e ortopédicos",
    "478": "Comércio varejista de produtos novos não especificados anteriormente e de produtos usados",
    "479": "Comércio ambulante e outros tipos de comércio varejista",
    "491": "Transporte ferroviário e metroferroviário",
    "492": "Transporte rodoviário de passageiros",
    "493": "Transporte rodoviário de carga",
    "494": "Transporte dutoviário",
    "495": "Trens turísticos, teleféricos e similares",
    "501": "Transporte marítimo de cabotagem e longo curso",
    "502": "Transporte por navegação interior",
    "503": "Navegação de apoio",
    "509": "Outros transportes aquaviários",
    "511": "Transporte aéreo de passageiros",
    "512": "Transporte aéreo de carga",
    "513": "Transporte espacial",
    "521": "Armazenamento, carga e descarga",
    "522": "Atividades auxiliares dos transportes terrestres",
    "523": "Atividades auxiliares dos transportes aquaviários",
    "524": "Atividades auxiliares dos transportes aéreos",
    "525": "Atividades relacionadas à organização do transporte de carga",
    "531": "Atividades de Correio",
    "532": "Atividades de malote e de entrega",
    "551": "Hotéis e similares",
    "559": "Outros tipos de alojamento não especificados anteriormente",
    "561": "Restaurantes e outros serviços de alimentação e bebidas",
    "562": "Serviços de catering, bufê e outros serviços de comida preparada",
    "581": "Edição de livros, jornais, revistas e outras atividades de edição",
    "582": "Edição integrada à impressão de livros, jornais, revistas e outras publicações",
    "591": "Atividades cinematográficas, produção de vídeos e de programas de televisão",
    "592": "Atividades de gravação de som e de edição de música",
    "601": "Atividades de rádio",
    "602": "Atividades de televisão",
    "611": "Telecomunicações por fio",
    "612": "Telecomunicações sem fio",
    "613": "Telecomunicações por satélite",
    "614": "Operadoras de televisão por assinatura",
    "619": "Outras atividades de telecomunicações",
    "620": "Atividades dos serviços de tecnologia da informação",
    "631": "Tratamento de dados, hospedagem na internet e outras atividades relacionadas",
    "639": "Outras atividades de prestação de serviços de informação",
    "641": "Banco Central",
    "642": "Intermediação monetária - depósitos à vista",
    "643": "Intermediação não-monetária - outros instrumentos de captação",
    "644": "Arrendamento mercantil",
    "645": "Sociedades de capitalização",
    "646": "Atividades de sociedades de participação",
    "647": "Fundos de investimento",
    "649": "Atividades de serviços financeiros não especificadas anteriormente",
    "651": "Seguros de vida e não-vida",
    "652": "Seguros-saúde",
    "653": "Resseguros",
    "654": "Previdência complementar",
    "655": "Planos de saúde",
    "661": "Atividades auxiliares dos serviços financeiros",
    "662": "Atividades auxiliares dos seguros, da previdência complementar e dos planos de saúde",
    "663": "Atividades de administração de fundos por contrato ou comissão",
    "681": "Atividades imobiliárias de imóveis próprios",
    "682": "Atividades imobiliárias por contrato ou comissão",
    "691": "Atividades jurídicas",
    "692": "Atividades de contabilidade, consultoria e auditoria contábil e tributária",
    "701": "Sedes de empresas e unidades administrativas locais",
    "702": "Atividades de consultoria em gestão empresarial",
    "711": "Serviços de arquitetura e engenharia e atividades técnicas relacionadas",
    "712": "Testes e análises técnicas",
    "721": "Pesquisa e desenvolvimento experimental em ciências físicas e naturais",
    "722": "Pesquisa e desenvolvimento experimental em ciências sociais e humanas",
    "731": "Publicidade",
    "732": "Pesquisas de mercado e de opinião pública",
    "741": "Design e decoração de interiores",
    "742": "Atividades fotográficas e similares",
    "749": "Atividades profissionais, científicas e técnicas não especificadas anteriormente",
    "750": "Atividades veterinárias",
    "771": "Locação de meios de transporte sem condutor",
    "772": "Aluguel de objetos pessoais e domésticos",
    "773": "Aluguel de máquinas e equipamentos sem operador",
    "774": "Gestão de ativos intangíveis não-financeiros",
    "781": "Seleção e agenciamento de mão-de-obra",
    "782": "Locação de mão-de-obra temporária",
    "783": "Fornecimento e gestão de recursos humanos para terceiros",
    "791": "Agências de viagens e operadores turísticos",
    "799": "Serviços de reservas e outros serviços de turismo não especificados anteriormente",
    "801": "Atividades de vigilância, segurança privada e transporte de valores",
    "802": "Atividades de monitoramento de sistemas de segurança",
    "803": "Atividades de investigação particular",
    "811": "Serviços combinados para apoio a edifícios",
    "812": "Atividades de limpeza",
    "813": "Atividades paisagísticas",
    "821": "Serviços de escritório e apoio administrativo",
    "822": "Atividades de teleatendimento",
    "823": "Atividades de organização de eventos, exceto culturais e esportivos",
    "829": "Outras atividades de serviços prestados principalmente às empresas",
    "841": "Administração do estado e da política econômica e social",
    "842": "Serviços coletivos prestados pela administração pública",
    "843": "Seguridade social obrigatória",
    "851": "Educação infantil e ensino fundamental",
    "852": "Ensino médio",
    "853": "Educação superior",
    "854": "Educação profissional de nível técnico e tecnológico",
    "855": "Atividades de apoio à educação",
    "859": "Outras atividades de ensino",
    "861": "Atividades de atendimento hospitalar",
    "862": "Serviços móveis de atendimento a urgências e de remoção de pacientes",
    "863": "Atividades de atenção ambulatorial executadas por médicos e odontólogos",
    "864": "Atividades de serviços de complementação diagnóstica e terapêutica",
    "865": "Atividades de profissionais da área de saúde, exceto médicos e odontólogos",
    "866": "Atividades de apoio à gestão de saúde",
    "869": "Atividades de atenção à saúde humana não especificadas anteriormente",
    "871": "Atividades de assistência a idosos, deficientes físicos, imunodeprimidos e convalescentes, e de infra-estrutura e apoio a pacientes prestadas em residências coletivas e particulares",
    "872": "Atividades de assistência psicossocial e à saúde a portadores de distúrbios psíquicos, deficiência mental e dependência química",
    "873": "Atividades de assistência social prestadas em residências coletivas e particulares",
    "880": "Serviços de assistência social sem alojamento",
    "900": "Atividades artísticas, criativas e de espetáculos",
    "910": "Atividades ligadas ao patrimônio cultural e ambiental",
    "920": "Atividades de exploração de jogos de azar e apostas",
    "931": "Atividades esportivas",
    "932": "Atividades de recreação e lazer",
    "941": "Atividades de organizações associativas patronais, empresariais e profissionais",
    "942": "Atividades de organizações sindicais",
    "943": "Atividades de associações de defesa de direitos sociais",
    "949": "Atividades de organizações associativas não especificadas anteriormente",
    "951": "Reparação e manutenção de equipamentos de informática e comunicação",
    "952": "Reparação e manutenção de objetos e equipamentos pessoais e domésticos",
    "960": "Outras atividades de serviços pessoais",
    "970": "Serviços domésticos",
    "990": "Organismos internacionais e outras instituições extraterritoriais",
  };