export interface BruteData {
    "EMPRESA (SIGLA)": string;
    "EMPRESA (NOME)": string;
    "EMPRESA (NACIONALIDADE)": string;
    ANO: string;
    MÊS: string;
    "AEROPORTO DE ORIGEM (SIGLA)": string;
    "AEROPORTO DE ORIGEM (NOME)": string;
    "AEROPORTO DE ORIGEM (UF)": string;
    "AEROPORTO DE ORIGEM (REGIÃO)": string;
    "AEROPORTO DE ORIGEM (PAÍS)": string;
    "AEROPORTO DE ORIGEM (CONTINENTE)": string;
    "AEROPORTO DE DESTINO (SIGLA)": string;
    "AEROPORTO DE DESTINO (NOME)": string;
    "AEROPORTO DE DESTINO (UF)": string;
    "AEROPORTO DE DESTINO (REGIÃO)": string;
    "AEROPORTO DE DESTINO (PAÍS)": string;
    "AEROPORTO DE DESTINO (CONTINENTE)": string;
    NATUREZA: string;
    "GRUPO DE VOO": string;
    "PASSAGEIROS PAGOS": string;
    "PASSAGEIROS GRÁTIS": string;
    "CARGA PAGA (KG)": string;
    "CARGA GRÁTIS (KG)": string;
    "CORREIO (KG)": string;
    ASK: string;
    RPK: string;
    ATK: string;
    RTK: string;
    "COMBUSTÍVEL (LITROS)": string;
    "DISTÂNCIA VOADA (KM)": string;
    DECOLAGENS: string;
    "CARGA PAGA KM": string;
    "CARGA GRATIS KM": string;
    "CORREIO KM": string;
    ASSENTOS: string;
    PAYLOAD: string;
    "HORAS VOADAS": string;
    "BAGAGEM (KG)": string;
}
  